"""Advanced configuration dialog for FIDO2 authenticator.

This module provides the AdvancedConfigDialog class for managing advanced
configuration options including TPM keys, file-based platform keys, HKDF
configuration, and UHID device control.

Copyright IBM 2022, 2025
IBM Confidential
"""

import logging
import traceback

from PyQt6.QtWidgets import (
    QApplication,
    QDialog,
    QDialogButtonBox,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMessageBox,
    QPushButton,
    QVBoxLayout,
)
from PyQt6.QtCore import QThreadPool, Qt

try:
    from soft_fido2.qt.ux.workers import Worker
    from soft_fido2.qt.svc.platform_key_service import PlatformKeyService
except ImportError:
    from qt.ux.workers import Worker
    from qt.svc.platform_key_service import PlatformKeyService


class AdvancedConfigDialog(QDialog):
    """Advanced configuration dialog for power users.
    
    This dialog provides UI for:
    - TPM key management
    - File key management
    - HKDF configuration
    - Device restart
    
    Business logic is delegated to service classes.
    """
    
    TITLE = "Advanced Configuration"
    
    def __init__(self, parent, device_manager=None):
        """Initialize advanced config dialog.
        
        Args:
            parent: Parent dialog (typically SettingsDialog)
            device_manager: Optional device manager for UHID control
        """
        super().__init__(parent)
        self.setWindowTitle(self.TITLE)
        self.setModal(True)
        self.setWindowIcon(parent.windowIcon())
        
        self.parent_dialog = parent
        self.device_manager = device_manager
        self.tpm_available = parent.tpm_available
        self.fido_home = parent.fido_home
        self.platform_config = parent.parent().plat_cfg   
        self.delete_recreate_file_key_btn = None
        
        # Initialize service layer
        self.platform_key_service = PlatformKeyService(self.fido_home)
        
        # Build UI
        main_layout = QVBoxLayout()
        if device_manager:
            main_layout.addWidget(self._create_device_section())
        main_layout.addWidget(self._create_warning_label())
        main_layout.addWidget(self._create_tpm_section())
        main_layout.addWidget(self._create_file_key_section())
        main_layout.addWidget(self._create_hkdf_section())
        
        main_layout.addWidget(self._create_button_box())
        
        self.setLayout(main_layout)
        self.setMinimumWidth(550)
    
    def _create_warning_label(self):
        """Create warning label at top."""
        label = QLabel("⚠️  Advanced Settings - Changes can affect existing credentials")
        label.setStyleSheet("""
            QLabel {
                background-color: #fff3cd;
                color: #856404;
                border: 1px solid #ffeaa7;
                border-radius: 4px;
                padding: 10px;
                font-weight: bold;
            }
        """)
        label.setWordWrap(True)
        return label
    
    def _create_tpm_section(self):
        """Create TPM key management section."""
        group = QGroupBox("TPM Platform Key Management")
        layout = QVBoxLayout()
        
        # Status label
        self.tpm_status_label = QLabel()
        self._update_tpm_status()
        layout.addWidget(self.tpm_status_label)
        
        # Delete button
        self.delete_tpm_btn = QPushButton("Delete TPM Key")
        self.delete_tpm_btn.setEnabled(self.tpm_available)
        self.delete_tpm_btn.clicked.connect(self._handle_delete_tpm_key)
        layout.addWidget(self.delete_tpm_btn)
        
        # Warning label
        warning = QLabel("⚠️ Deleting the TPM key will make all existing User Presence Only (U2F) credentials inaccessible")
        warning.setStyleSheet("color: #d9534f; font-style: italic;")
        warning.setWordWrap(True)
        layout.addWidget(warning)
        
        group.setLayout(layout)
        return group
    
    def _create_file_key_section(self):
        """Create file-based platform key management section."""
        group = QGroupBox("File-based Platform Key Management")
        layout = QVBoxLayout()
        
        # Status label
        self.file_key_status_label = QLabel()
        self._update_file_key_status()
        layout.addWidget(self.file_key_status_label)
        
        # Delete button
        self.delete_recreate_file_key_btn = QPushButton("Delete File-based Platform Key")
        self.delete_recreate_file_key_btn.setToolTip(
            "Delete file-based platform key\n\n"
            "WARNING: All UP only credentials generated by this key will be lost!\n"
            "You can recreate it using 'Create Platform Key' in the main menu."
        )
        self.delete_recreate_file_key_btn.clicked.connect(self._handle_delete_recreate_file_key)
        layout.addWidget(self.delete_recreate_file_key_btn)
        
        # Warning label
        warning = QLabel("⚠️ Deleting the file-based platform key will invalidate ALL existing credentials and registrations, including U2F User Presence (UP) only registrations which cannot be easily tracked or recovered")
        warning.setStyleSheet("color: #d9534f; font-style: italic;")
        warning.setWordWrap(True)
        layout.addWidget(warning)
        
        group.setLayout(layout)
        return group
    
    def _create_hkdf_section(self):
        """Create HKDF info string configuration section."""
        group = QGroupBox("Passkey Seed Derivation")
        layout = QVBoxLayout()
        
        # Description
        desc = QLabel("Info String (used in passkey binding function):")
        layout.addWidget(desc)
        
        # Input field
        input_layout = QHBoxLayout()
        self.info_input = QLineEdit()
        self.info_input.setText(self.platform_config.info_string)
        self.info_input.setPlaceholderText("FIDO2-PASSKEY-SEED")
        input_layout.addWidget(self.info_input)
        
        # Update button
        self.update_info_btn = QPushButton("Update")
        self.update_info_btn.clicked.connect(self._handle_update_info)
        input_layout.addWidget(self.update_info_btn)
        
        layout.addLayout(input_layout)
        
        # Warning
        warning = QLabel("⚠️ Changing this will make existing credentials inaccessible. "
                        "Only change if you understand the implications.")
        warning.setStyleSheet("color: #d9534f; font-style: italic;")
        warning.setWordWrap(True)
        layout.addWidget(warning)
        
        # Current value display
        current = QLabel(f"Current value: {self.platform_config.info_string}")
        current.setStyleSheet("color: #666; font-size: 10pt;")
        layout.addWidget(current)
        
        group.setLayout(layout)
        return group
    
    def _create_device_section(self):
        """Create UHID device control section."""
        group = QGroupBox("UHID Device Control")
        layout = QVBoxLayout()
        
        # Status label
        self.device_status_label = QLabel()
        self._update_device_status()
        layout.addWidget(self.device_status_label)
        
        # Restart button
        self.restart_device_btn = QPushButton("Restart UHID Device")
        self.restart_device_btn.clicked.connect(self._handle_restart_device)
        layout.addWidget(self.restart_device_btn)
        
        # Info label
        info = QLabel("Restarts the USB HID device without closing the application. "
                     "Use this if the device becomes unresponsive.")
        info.setStyleSheet("color: #666; font-style: italic;")
        info.setWordWrap(True)
        layout.addWidget(info)
        
        group.setLayout(layout)
        return group
    
    def _create_button_box(self):
        """Create button box with Close button."""
        button_box = QDialogButtonBox(QDialogButtonBox.StandardButton.Close)
        button_box.rejected.connect(self.close)
        return button_box
    
    def _update_tpm_status(self):
        """Update TPM status label."""
        if self.tpm_available:
            # Check if key exists using service layer
            try:
                has_key = self.platform_key_service.check_key_exists('tpm')
                if has_key:
                    self.tpm_status_label.setText("✓ TPM available, key exists")
                    self.tpm_status_label.setStyleSheet("color: green;")
                else:
                    self.tpm_status_label.setText("✓ TPM available, no key found")
                    self.tpm_status_label.setStyleSheet("color: orange;")
            except Exception as e:
                logging.warning(f"Error checking TPM status: {e}")
                self.tpm_status_label.setText("✓ TPM available, status unknown")
                self.tpm_status_label.setStyleSheet("color: orange;")
        else:
            self.tpm_status_label.setText("✗ TPM not available")
            self.tpm_status_label.setStyleSheet("color: red;")
    
    def _update_device_status(self):
        """Update device status label."""
        if self.device_manager and hasattr(self.device_manager, 'is_running') and self.device_manager.is_running():
            self.device_status_label.setText("✓ UHID device is running")
            self.device_status_label.setStyleSheet("color: green;")
        else:
            self.device_status_label.setText("✗ UHID device is not running")
            self.device_status_label.setStyleSheet("color: red;")

    def _update_file_key_status(self):
        """Update file-based platform key status label."""
        # Use service layer to check key existence
        has_key = self.platform_key_service.check_key_exists('file')
        
        if has_key:
            self.file_key_status_label.setText("✓ File-based platform key exists")
            self.file_key_status_label.setStyleSheet("color: green;")
            if self.delete_recreate_file_key_btn:
                self.delete_recreate_file_key_btn.setEnabled(True)
        else:
            self.file_key_status_label.setText("✗ No file-based platform key found")
            self.file_key_status_label.setStyleSheet("color: orange;")
            if self.delete_recreate_file_key_btn:
                self.delete_recreate_file_key_btn.setEnabled(False)
    
    def _handle_delete_tpm_key(self):
        """Handle TPM key deletion using service layer."""
        try:
            # Confirmation dialog
            reply = QMessageBox.question(
                self,
                "Confirm TPM Key Deletion",
                "Are you sure you want to delete the TPM platform key?\n\n"
                "This will make all TPM-derived credentials inaccessible.\n"
                "This action cannot be undone.",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No
            )
            
            if reply == QMessageBox.StandardButton.Yes:
                try:
                    from soft_fido2.platform.tpm_device import TPMDevice
                    tpm = TPMDevice()
                    tpm.delete_key()

                    # Remove the password-protected sentinel so the UI does
                    # not show the password field after the key is gone.
                    self.platform_key_service._remove_tpm_password_flag()

                    QMessageBox.information(
                        self,
                        "Success",
                        "TPM key deleted successfully."
                    )
                    
                    self._update_tpm_status()
                    
                    # Notify parent to update UI
                    if hasattr(self.parent_dialog, '_check_cache_key_status'):
                        self.parent_dialog._check_cache_key_status()
                    
                except Exception as e:
                    QMessageBox.critical(
                        self,
                        "Error",
                        f"Failed to delete TPM key:\n{str(e)}"
                    )
        except Exception as e:
            logging.error(f"Unhandled exception in _handle_delete_tpm_key: {e}")
            traceback.print_exc()
            QMessageBox.critical(
                self,
                "Unexpected Error",
                f"An unexpected error occurred:\n{str(e)}"
            )

    def _handle_delete_recreate_file_key(self):
        """Handle file-based platform key deletion using service layer."""
        try:
            # Confirmation dialog with detailed warning
            reply = QMessageBox.question(
                self,
                "Confirm File-based Platform Key Deletion",
                "Are you sure you want to delete the file-based platform key?\n\n"
                "WARNING: This will invalidate existing credentials generated by this key,\n"
                "including U2F User Presence (UP) only registrations which cannot be easily\n"
                "tracked or recovered.\n\n"
                "You will need to re-register with these services.\n\n"
                "You can generate a new key using 'Create Platform Key (+)' in the main menu.\n\n"
                "This action cannot be undone.",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No
            )
            
            if reply == QMessageBox.StandardButton.Yes:
                try:
                    # Show loading cursor
                    QApplication.setOverrideCursor(Qt.CursorShape.WaitCursor)
                    
                    # Use service layer to delete file key
                    success, message = self.platform_key_service.delete_file_key()
                    
                    # Restore normal cursor
                    QApplication.restoreOverrideCursor()
                    
                    if success:
                        QMessageBox.information(
                            self,
                            "Success",
                            "File-based platform key deleted successfully.\n\n"
                            "You can recreate it using 'Create Platform Key' in the main menu."
                        )
                    else:
                        QMessageBox.information(
                            self,
                            "Info",
                            message
                        )
                    
                    self._update_file_key_status()
                    
                    # Notify parent to update UI
                    if hasattr(self.parent_dialog, '_update_cache_status'):
                        self.parent_dialog._update_cache_status()
                    
                except Exception as e:
                    # Restore cursor on error
                    QApplication.restoreOverrideCursor()
                    QMessageBox.critical(
                        self,
                        "Error",
                        f"Failed to delete file-based platform key:\n{str(e)}"
                    )
        except Exception as e:
            logging.error(f"Unhandled exception in _handle_delete_recreate_file_key: {e}")
            traceback.print_exc()
            QMessageBox.critical(
                self,
                "Unexpected Error",
                f"An unexpected error occurred:\n{str(e)}"
            )
    
    def _handle_update_info(self):
        """Handle info string update."""
        try:
            new_info = self.info_input.text().strip()
            
            if not new_info:
                QMessageBox.warning(
                    self,
                    "Invalid Input",
                    "Info string cannot be empty."
                )
                return
            
            if new_info == self.platform_config.info_string:
                QMessageBox.information(
                    self,
                    "No Change",
                    "The info string is already set to this value."
                )
                return
            
            # Confirmation dialog
            reply = QMessageBox.question(
                self,
                "Confirm Info Update",
                f"Are you sure you want to change the info string?\n\n"
                f"Current: {self.platform_config.info_string}\n"
                f"New: {new_info}\n\n"
                f"This will make all existing credentials inaccessible.\n"
                f"This action cannot be undone.",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No
            )
            
            if reply == QMessageBox.StandardButton.Yes:
                try:
                    self.platform_config.info_string = new_info
                    
                    QMessageBox.information(
                        self,
                        "Success",
                        f"Info string updated to: {new_info}\n\n"
                        f"Existing credentials will no longer be accessible."
                    )
                    
                except Exception as e:
                    QMessageBox.critical(
                        self,
                        "Error",
                        f"Failed to update HKDF info string:\n{str(e)}"
                    )
        except Exception as e:
            logging.error(f"Unhandled exception in _handle_update_info: {e}")
            traceback.print_exc()
            QMessageBox.critical(
                self,
                "Unexpected Error",
                f"An unexpected error occurred:\n{str(e)}"
            )
    
    def _handle_restart_device(self):
        """Handle UHID device restart."""
        try:
            if not self.device_manager:
                QMessageBox.warning(
                    self,
                    "Not Available",
                    "Device manager not available."
                )
                return
            
            # Confirmation dialog
            reply = QMessageBox.question(
                self,
                "Confirm Device Restart",
                "Are you sure you want to restart the UHID device?\n\n"
                "This will briefly interrupt FIDO2 operations.",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No
            )
            
            if reply == QMessageBox.StandardButton.Yes:
                try:
                    self.restart_device_btn.setEnabled(False)
                    self.restart_device_btn.setText("Restarting...")
                    
                    # Restart in background thread using Worker pattern
                    def restart_worker():
                        try:
                            if self.device_manager:
                                self.device_manager.restart_device()
                            return (True, "Device restarted successfully")
                        except Exception as e:
                            return (False, str(e))
                    
                    # Create worker and connect signals
                    worker = Worker(restart_worker)
                    
                    def on_restart_complete(result):
                        """Handle restart completion with result."""
                        try:
                            self.restart_device_btn.setEnabled(True)
                            self.restart_device_btn.setText("Restart UHID Device")
                            self._update_device_status()
                            
                            success, message = result
                            if success:
                                QMessageBox.information(self, "Success", message)
                            else:
                                QMessageBox.critical(self, "Error", f"Failed to restart device:\n{message}")
                        except Exception as e:
                            logging.error(f"Error in on_restart_complete: {e}")
                            traceback.print_exc()
                    
                    def on_restart_error(error_info):
                        """Handle restart error."""
                        try:
                            self.restart_device_btn.setEnabled(True)
                            self.restart_device_btn.setText("Restart UHID Device")
                            exctype, value, tb = error_info
                            QMessageBox.critical(
                                self,
                                "Error",
                                f"Failed to restart device:\n{value}"
                            )
                        except Exception as e:
                            logging.error(f"Error in on_restart_error: {e}")
                            traceback.print_exc()
                    
                    # Connect signals
                    worker.signals.result.connect(on_restart_complete)
                    worker.signals.error.connect(on_restart_error)
                    
                    # Execute worker in thread pool
                    thread_pool = QThreadPool.globalInstance()
                    if thread_pool:  # Type checker satisfaction (always true)
                        thread_pool.start(worker)
                    
                except Exception as e:
                    self.restart_device_btn.setEnabled(True)
                    self.restart_device_btn.setText("Restart UHID Device")
                    QMessageBox.critical(
                        self,
                        "Error",
                        f"Failed to restart device:\n{str(e)}"
                    )
        except Exception as e:
            logging.error(f"Unhandled exception in _handle_restart_device: {e}")
            traceback.print_exc()
            QMessageBox.critical(
                self,
                "Unexpected Error",
                f"An unexpected error occurred:\n{str(e)}"
            )
