dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install curl

install:
  - pip install -r requirements.txt

script: 
  - ./build.sh

stages:
  - unit_test
  - scenario_test
  - deploy

jobs:
  include:
    - stage: unit_test
      script:
        - ./python_authenticator/tests/unit_test.sh
      python:
        - "3.7"
    - stage: scenario_test
      script:
        - ./python_authenticator/tests/scenario_test.sh
      python:
        - "3.7"
    - stage: deploy
      script: 
        - ./deploy
      python:
        - "3.7"
      if: branch = master
