dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt

script: ./compile

stages:
  - run_tests
  - deploy

jobs:
  include:
    - stage: run_tests
      script: 
        - ./unit_test
        - ./scenario_test
      python:
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7"
    - stage: deploy
      script: 
        - ./deploy
      python:
        - "3.7"
      if: branch = master
